### ISSUE TITLE
Function signature for $zip should include context and return an array <a+-:a>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#302] opened 2019-02-25 15:16 UTC
$zip function signature shows only <a+> but should be <a+-:a>

However, [2,3].$zip([1,2,3]) does not return the expected result that is returned by [2,3]~>$zip([1,2,3]), or by $zip([2,3],[1,2,3])
[
  [
    2,
    1
  ],
  [
    3,
    2
  ]
]

**Comment by andrew-coleman** [comment] 2019-03-08 10:38
I'm not sure what you are asking for here.  The zip function works on one or more arrays, which is what the signature `<a+>` specifies (strictly speaking the signature should be `<a+:a>` to specify the return type, but the evaluator doesn't do type checking on that yet). 

I'm not sure what you're expecting `[2,3].$zip([1,2,3])` to do.  It will evaluate the zip function twice, first with `2` as the context value, then `3`.  However, the zip function is ignoring the context (unless you explicitly refer to it using `$`).

I think this is working as designed.

**Comment by andrew-coleman** [comment] 2019-03-08 11:23
Duplicate of #305

**Closed by andrew-coleman** 2019-03-08 11:23 UTC
