### ISSUE TITLE
$sort function signature should show ability to use context variable and take any variable type <x-f?:a>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#309] opened 2019-02-25 16:20 UTC

**Comment by wnm3** [comment] 2019-02-25 16:22
"a"~>$sort(function($a,$b){$a>$b} works as does "a"~>$sort()

**Comment by andrew-coleman** [comment] 2019-03-08 11:22
Duplicate of #305

**Closed by andrew-coleman** 2019-03-08 11:22 UTC
