### ISSUE TITLE
create-react-app - 'npm run build' - fails

### ISSUE THREAD

**Issue by moccadroid** [jsonata-js/jsonata#214] opened 2018-04-24 15:22 UTC
When I use jsonata with create-react-app it fails when running 'npm run build' with the following error:

    Failed to minify the code from this file:
    ./node_modules/jsonata/jsonata.js:1464
    Read more here: http://bit.ly/2tRViJ9

according to the link I should open up a ticket for this on the dependency's issue tracker :)
please fix this? :D

**Comment by xogeny** [comment] 2018-04-24 16:29
I suspect this is actually a duplicate of #211.  You should be able to do an `npm run start` no problem, right?  It is just the build that is failing.  This is because the minifier doesn't support es6 syntax (which seems long over due, to me...but I digress).

**Comment by s100** [comment] 2018-05-25 10:56
So, `package.json`'s `"main"` property points to `jsonata-es5.js` (pure ES5) whereas its `"module"` property (intended for consumers which understand ES6 modules) points to `jsonata.js` (ES6 with `yield*` and suchlike all over the place). It's disappointing that support for ES6 modules is so out of whack with support for ES6 generators, but the bottom line is I think we need to move the *original* ES6+generators source to a separate file, and transpile away that generator syntax when constructing `jsonata.js` for consumers.

**Comment by xogeny** [comment] 2018-05-25 14:32
Just a comment...in my TypeScript based implementation there is no generator syntax.  Now, part of the reason is that my goal was to separate out the semantics of JSONata from how values were resolved.  So my current version only supports synchronous evaluation.  My goal is to actually incorporate async (promises, generators and/or observables) but I wanted to handle that as a separate concern since there are so many potential ways that values could be resolved and I didn't want to repeat all the semantics for each case.

Also note that because the code base is in TypeScript, it is possible to transpile to both es5 or es6 from the same (TypeScript) code base.

Unfortunately, that work is still ongoing.  But I just wanted to point out my goals.

**Comment by andrew-coleman** [comment] 2018-12-17 14:06
I've done a quick test to confirm that this works with jsonata v1.6.1.
The following create-react-app code builds and runs without error:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import jsonata from 'jsonata';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
            <p>JSONata: {jsonata('$formatInteger(1234, "w")').evaluate({})}</p>
          <p>Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;
```

```
$ npm run build

> jsonata-app@0.1.0 build create-react-app/jsonata-app
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  59.49 KB  build/static/js/1.b2428ee8.chunk.js
  770 B     build/static/js/main.5e34aaee.chunk.js
  763 B     build/static/js/runtime~main.229c360f.js
  510 B     build/static/css/main.d1ed87cb.chunk.css
```

**Closed by andrew-coleman** 2018-12-17 14:06 UTC
