### ISSUE TITLE
Adding empty array brackets to query now wraps arrays with extra array instead of just ensuring that output is an array

### ISSUE THREAD

**Issue by timkindberg** [jsonata-js/jsonata#526] opened 2021-06-22 18:26 UTC
1.8.4 BROKEN: https://try.jsonata.org/SycA90CIE
![image](https://user-images.githubusercontent.com/168046/122979193-43591000-d365-11eb-9d3e-28ae58f4f388.png)

1.6.5 WORKS: The exerciser doesn't save the version, so you have to update the version dropdown manually. But here is a screenshot:
![image](https://user-images.githubusercontent.com/168046/122979163-39cfa800-d365-11eb-8419-328791e4e77e.png)

We have so many transforms saved into our DB that add the `[]` to a query to ensure an array output. This will crush our app if I update.

The docs even promote this pattern in [this section](http://docs.jsonata.org/predicate#singleton-array-and-value-equivalence), so I'm hoping I'm right here:
> If this is a concern, then the expression can be modified to make it return an array even if only a single value is matched. This is done by adding empty square brackets [] to a step within the location path. The examples above can be re-written to always return an array as follows:

> Address[].City returns [ "Winchester"]
Phone[0][].number returns [ "0203 544 1234" ]
Phone[][type='home'].number returns [ "0203 544 1234" ]
Phone[type='office'].number[] returns [ "01962 001234", "01962 001235" ]
Note that the [] can be placed either side of the predicates and on any step in the path expression

**Comment by jhorbulyk** [comment] 2021-06-23 07:52
Related: https://github.com/jsonata-js/jsonata/issues/462

**Comment by natcl** [comment] 2021-08-04 23:10
Any chance this  could be fixed ?

**Comment by natcl** [comment] 2021-08-04 23:20
What is really strange is that if the above example is wrapped into an array, then it behaves as expected:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/77556/128267772-a5bfcce7-05dc-4e55-a2f5-6b5e13b19979.png">

**Comment by andrew-coleman** [comment] 2021-08-18 08:06
Closing as duplicate of #462 (PR created)

**Closed by andrew-coleman** 2021-08-18 08:06 UTC
