### ISSUE TITLE
And  

### ISSUE THREAD

**Issue by E1cid** [jsonata-js/jsonata#505] opened 2021-03-13 11:38 UTC
hope i explain this correctly. using node-red and jsonata.

Ok expression ($type(test1) = "number" and test1 > 10 )
 test 1 = "test"
now if test is not a number, why does the expression contine to to the and condition?

This cause the jsonata to throw an error as test1 is then compared to a number.

If the first condition of an and expression is false then the others need not be tested.

If there is another way to avoid the error could you please point it out.

**Comment by jhorbulyk** [comment] 2021-03-15 13:44
Possible duplicate of #338

**Comment by E1cid** [comment] 2021-03-15 13:50
Cheers, for reply i did that work around after i posted.
Is there any plan to have the and condition return after first condition fails?

**Comment by andrew-coleman** [comment] 2021-03-15 16:22
resolved by #506

**Closed by andrew-coleman** 2021-03-15 16:22 UTC
