### ISSUE TITLE
$lookup function signature should be <o-s:x>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#304] opened 2019-02-25 15:23 UTC
The $lookup function operates on an object passed or via context variable but its function signature claims it works with anything (<x-s:x>)

**Comment by andrew-coleman** [comment] 2019-03-08 11:01
This is a similar issue to [this one](https://github.com/jsonata-js/jsonata/issues/303#issuecomment-470889457)

**Comment by andrew-coleman** [comment] 2019-07-04 06:43
Closing since I believe this is working as designed

**Closed by andrew-coleman** 2019-07-04 06:43 UTC
