### ISSUE TITLE
Native Java implementation for jsonata

### ISSUE THREAD

**Issue by anauti1** [jsonata-js/jsonata#251] opened 2018-08-05 00:37 UTC
Hi All,
I am evaluating jsonata tool for an expression query tool we plan to build.
Was wondering if as mentioned here  a native Java implementation of jsonata is available for use. I am seeking for some examples that can help me to use jsonata from Java and vice versa and lets me run on JVM.
https://developer.ibm.com/open/2017/02/28/announcing-jsonata-v1-1/ 
Thanks!

**Comment by mattbaileyuk** [comment] 2018-08-28 15:59
I'm afraid there isn't currently a native Java implementation available; while I'm aware of one being developed, I don't know the current status (or whether it will be made publicly available and/or open sourced).

As seen on some other issues on here there have been some people trying out JavaScript interpreters in Java with mixed success in order to use JSONata in a Java world.

**Comment by xogeny** [comment] 2018-08-28 16:57
I wonder if this might be an option for some people:

https://github.com/graalvm/graaljs

I think the previous discussions I've seen involved Javascript interpreters written in Java running on the JVM.  This is slightly different I think.

**Comment by Allam76** [comment] 2018-09-04 13:50
I just finished a jsonata implementation in a very old fashioned language called ABAP. So if that works than it should work in any modern language:-)
For java the pratt algorithm [here:](https://github.com/forax/pratt_parser) is of special interest since it is functional based with java 9. As you see it is quite elegant.

There is also a more traditional approach [here](https://github.com/xoom/prattparser-java)

After that is is mostly to translate the jsonata code.... Took me 4 days so for someone with good java skills it would be even less.

If is important to understand the steps:
1) Pratt algorithm
2) Lexing of the tokens
3) Parsing to nodes
4) AST optimization
5) Evaluation 
Best is to keep as close to the jsonata as possible. There is a tremendous amount of thinking invested that you really don't want to reinvent. Stay away from trying to simplify the code too much.

Also use good unit tests. This kind of stuff is very prone to regression.

**Comment by andrew-coleman** [comment] 2018-10-24 08:37
Closing this issue - thanks for the discussion

**Closed by andrew-coleman** 2018-10-24 08:37 UTC
